apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openmrs-deploy
spec:
  replicas: 3
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: openmrs
    spec:
      containers:
      - name: openmrs
        image: alex7777/openmrs
        ports:
        - containerPort: 8080
